# Generated by Django 2.2.16 on 2021-06-14 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0002_auto_20210614_1209'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0002_administracion_code_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Crear'), ('R', 'Leer'), ('U', 'Editar'), ('D', 'Borrar')], default='R', max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=50)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=50)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=50)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterModelOptions(
            name='administracion',
            options={'verbose_name': 'Modulo de Administracion', 'verbose_name_plural': 'Modulos de Administracion'},
        ),
        migrations.CreateModel(
            name='asignarProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=50)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('permiso', models.ManyToManyField(to='administracion.Permisos')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo.Proyectos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '- Asignar Proyecto',
                'verbose_name_plural': 'Asignar Proyectos',
            },
        ),
    ]
