# Generated by Django 2.2.16 on 2021-06-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20210614_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracion',
            name='code_url',
            field=models.CharField(max_length=200),
        ),
    ]
