# Generated by Django 2.2.16 on 2021-06-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20210614_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignarproyecto',
            options={'ordering': ['-create'], 'verbose_name': '- Asignar Proyecto', 'verbose_name_plural': 'Asignar Proyectos'},
        ),
    ]
