# Generated by Django 3.1.6 on 2021-06-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desarrollo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.CharField(max_length=200)),
                ('code_url', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='configuracion')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modulo Gestion de Configuracion',
                'verbose_name_plural': 'Modulo Gestion de Configuracion',
            },
        ),
        migrations.CreateModel(
            name='lineaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('tarea_proy', models.ManyToManyField(to='desarrollo.asignarTareas')),
                ('tareas', models.ManyToManyField(to='desarrollo.Tareas')),
            ],
            options={
                'verbose_name': 'linea base',
                'verbose_name_plural': 'lineas bases',
            },
        ),
    ]
