# Generated by Django 2.2.16 on 2021-06-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='code_url',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
