# Generated by Django 3.1.6 on 2021-06-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineabase',
            name='tareas',
        ),
    ]
