# Generated by Django 2.2.16 on 2021-06-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configuracion_code_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='code_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='contenido',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
