# Generated by Django 3.1.6 on 2021-06-15 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='asignarTareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('version', models.CharField(default='1', max_length=50)),
                ('prioridad', models.CharField(choices=[('A', 'Alta'), ('B', 'Baja'), ('M', 'Media')], default='B', max_length=50)),
                ('observacion', models.CharField(default='', max_length=500)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea por proyecto',
                'verbose_name_plural': 'Tareas por proyectos',
            },
        ),
        migrations.CreateModel(
            name='Desarrollo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='desarrollo')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('code_url', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Modulo de desarrollo',
                'verbose_name_plural': 'Modulos de desarrollo',
            },
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('nivel_herencia', models.IntegerField(default=0)),
                ('orden_ejecucion', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('I', 'Iniciado'), ('P', 'Pendiente'), ('F', 'Finalizado')], default='P', max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('proy_tarea_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tarea_padre', to='desarrollo.tareas')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('I', 'Iniciado'), ('P', 'Pendiente'), ('F', 'Finalizado')], default='P', max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('tareasProy', models.ManyToManyField(through='desarrollo.asignarTareas', to='desarrollo.Tareas')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
            },
        ),
        migrations.AddField(
            model_name='asignartareas',
            name='proyectos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo.proyectos'),
        ),
        migrations.AddField(
            model_name='asignartareas',
            name='tareas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo.tareas'),
        ),
    ]
