# Generated by Django 2.2.16 on 2021-06-14 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desarrollo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignarTareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('version', models.CharField(default='1', max_length=50)),
                ('prioridad', models.CharField(choices=[('A', 'Alta'), ('B', 'Baja'), ('M', 'Media')], default='B', max_length=50)),
                ('observacion', models.CharField(default='', max_length=500)),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea por proyecto',
                'verbose_name_plural': 'Tareas por proyectos',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('I', 'Iniciado'), ('P', 'Pendiente'), ('F', 'Finalizado')], default='P', max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
            },
        ),
        migrations.AlterModelOptions(
            name='desarrollo',
            options={'verbose_name': 'Modulo de desarrollo', 'verbose_name_plural': 'Modulos de desarrollo'},
        ),
        migrations.AddField(
            model_name='desarrollo',
            name='code_url',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('I', 'Iniciado'), ('P', 'Pendiente'), ('F', 'Finalizado')], default='P', max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('tareasProy', models.ManyToManyField(through='desarrollo.asignarTareas', to='desarrollo.Proyectos')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
            },
        ),
        migrations.CreateModel(
            name='Dependencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('nivel_herencia', models.IntegerField(default=1)),
                ('orden_ejecucion', models.IntegerField(default=1)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=50)),
                ('proy_tarea_hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proy_tarea_hijo_id', to='desarrollo.asignarTareas')),
                ('proy_tarea_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proy_tarea_padre_id', to='desarrollo.asignarTareas')),
            ],
            options={
                'verbose_name': 'dependencia',
                'verbose_name_plural': 'dependencias',
            },
        ),
        migrations.AddField(
            model_name='asignartareas',
            name='proyectos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo.Proyectos'),
        ),
        migrations.AddField(
            model_name='asignartareas',
            name='tareas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo.Tareas'),
        ),
    ]
