# Generated by Django 3.1.6 on 2021-04-09 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desarrollo', '0002_proyectos_tareas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='encargado',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='encargado',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
