# Generated by Django 2.2.16 on 2021-06-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0002_auto_20210614_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectos',
            options={'verbose_name': 'tarea', 'verbose_name_plural': 'tareas'},
        ),
        migrations.AlterModelOptions(
            name='tareas',
            options={},
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='tareasProy',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='tareasProy',
            field=models.ManyToManyField(through='desarrollo.asignarTareas', to='desarrollo.Tareas'),
        ),
        migrations.AddField(
            model_name='tareas',
            name='nivel_herencia',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tareas',
            name='orden_ejecucion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tareas',
            name='proy_tarea_padre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_tarea_padre', to='desarrollo.Tareas'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Dependencias',
        ),
    ]
