# Generated by Django 3.1.6 on 2021-04-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0003_auto_20210408_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('proy_tarea_padre', models.IntegerField()),
                ('proy_tarea_hijo', models.IntegerField()),
                ('nivel_herencia', models.IntegerField()),
                ('orden_ejecucion', models.IntegerField()),
                ('create', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=50)),
            ],
            options={
                'verbose_name': 'dependencia',
                'verbose_name_plural': 'dependencias',
            },
        ),
    ]
