# Generated by Django 2.2.16 on 2021-06-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0003_auto_20210614_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectos',
            options={'verbose_name': 'proyecto', 'verbose_name_plural': 'proyectos'},
        ),
        migrations.AlterModelOptions(
            name='tareas',
            options={'verbose_name': 'tarea', 'verbose_name_plural': 'tareas'},
        ),
        migrations.RenameField(
            model_name='asignartareas',
            old_name='descripcion',
            new_name='titulo',
        ),
    ]
