# Generated by Django 2.2.16 on 2021-06-14 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0004_auto_20210614_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='proy_tarea_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_tarea_padre', to='desarrollo.Tareas'),
        ),
    ]
