# Generated by Django 2.2.16 on 2021-06-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0005_auto_20210614_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='nivel_herencia',
            field=models.IntegerField(default=0),
        ),
    ]
