# Generated by Django 3.1.6 on 2021-04-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0005_desarrollo_code_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desarrollo',
            name='code_url',
        ),
    ]
