# Generated by Django 3.1.6 on 2021-04-09 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desarrollo', '0007_desarrollo_code_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='desarrollo_proyecto_tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('encargado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyectos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo.proyectos')),
                ('tareas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desarrollo.tareas')),
            ],
        ),
        migrations.AlterField(
            model_name='dependencias',
            name='proy_tarea_hijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proy_tarea_hijo', to='desarrollo.desarrollo_proyecto_tareas'),
        ),
        migrations.AlterField(
            model_name='dependencias',
            name='proy_tarea_padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proy_tarea_padre', to='desarrollo.desarrollo_proyecto_tareas'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='proyecto_tareas',
            field=models.ManyToManyField(through='desarrollo.desarrollo_proyecto_tareas', to='desarrollo.Proyectos'),
        ),
    ]
