# Generated by Django 3.1.6 on 2021-04-09 22:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desarrollo', '0008_auto_20210409_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='desarrollo_proyecto_tareas',
            new_name='desarrollo_tareas_proyecto_tareas',
        ),
    ]
