# Generated by Django 3.1.6 on 2021-04-09 22:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desarrollo', '0009_auto_20210409_1824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='desarrollo_tareas_proyecto_tareas',
            new_name='desarrollo_proyecto_tareas',
        ),
        migrations.RenameField(
            model_name='dependencias',
            old_name='proy_tarea_hijo',
            new_name='proy_tarea_hijo_id',
        ),
        migrations.RenameField(
            model_name='dependencias',
            old_name='proy_tarea_padre',
            new_name='proy_tarea_padre_id',
        ),
    ]
