# Generated by Django 3.1.6 on 2021-04-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0010_auto_20210409_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependencias',
            old_name='proy_tarea_hijo_id',
            new_name='proy_tarea_hijo',
        ),
        migrations.RenameField(
            model_name='dependencias',
            old_name='proy_tarea_padre_id',
            new_name='proy_tarea_padre',
        ),
    ]
