# Generated by Django 3.1.6 on 2021-04-09 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desarrollo', '0012_auto_20210409_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='desarrollo_tareas_proyecto_tareas',
            new_name='proyecto_tareas',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='proyecto_tareas',
        ),
        migrations.AddField(
            model_name='tareas',
            name='tareasProy',
            field=models.ManyToManyField(through='desarrollo.proyecto_tareas', to='desarrollo.Proyectos'),
        ),
    ]
