# Generated by Django 3.1.6 on 2021-04-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0013_auto_20210409_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto_tareas',
            old_name='encargado_id',
            new_name='encargado',
        ),
        migrations.RenameField(
            model_name='proyecto_tareas',
            old_name='proyectos_id',
            new_name='proyectos',
        ),
        migrations.RenameField(
            model_name='proyecto_tareas',
            old_name='tareas_id',
            new_name='tareas',
        ),
    ]
