# Generated by Django 3.1.6 on 2021-04-09 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0014_auto_20210409_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_tareas',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
