# Generated by Django 3.1.6 on 2021-04-09 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0016_auto_20210409_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencias',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dependencias',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
