# Generated by Django 3.1.6 on 2021-04-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0017_auto_20210409_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollo',
            name='code_url',
            field=models.CharField(max_length=250),
        ),
    ]
