# Generated by Django 3.1.6 on 2021-04-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desarrollo', '0018_auto_20210409_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_tareas',
            name='observacion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='proyecto_tareas',
            name='prioridad',
            field=models.CharField(choices=[('A', 'Alta'), ('B', 'Baja'), ('M', 'Media')], default='B', max_length=50),
        ),
        migrations.AddField(
            model_name='proyecto_tareas',
            name='version',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='dependencias',
            name='nivel_herencia',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dependencias',
            name='orden_ejecucion',
            field=models.IntegerField(default=1),
        ),
    ]
